Private-Events Projects
brugobi/private-events pull request #4
Opened 2020-08-06 21:25 UTC by emiliocm9

### This project had the aim to build a private social club which allows the client to interact with the server to create new users, new events and decide the attendance of every event created. This projects has the next features:

- [x] The client can create new users.
- [x] Every user has the opportunity to create new events and set an attendance list.
- [x] Every user has the opportunity to decide the events to attend.
- [x] The events are separated in two different lists: upcoming events and previous events.
- [x] All users have to have an username and a password to get accepted in the club.
- [x] The app has been developed on Heroku.
- [x] Bootstrap has been used to style the app layout.

2020-08-07 07:33 UTC, mosesogwo requested changes
**Hello! :wave:. Good job here :+1:. Let's now make the following fixes:**

:point_right: The user's show page should display events the user has created and events that the user is attending to separated in past and upcoming. Currently, the page shows all events (ones that he didn't create and is not attending shouldn't be shown). Remember to group them into past and upcoming.


![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)


:point_right: In line with the above, your UsersController show action should retrieve these three collections for use in the views: _his created events_, _his attended_events (past)_, _attended_events (upcoming)_



:point_right: Let's add navigation links at the top of the page. Users should be able to navigate to create new event, login, logout and visit the home page from any view. The navigation links will be appropriate in Application Layout.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png)



_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-08-07 07:33 UTC, mosesogwo commented on app/controllers/events_controller.rb
> +    # @prev_events = current_user.previous_events
Remove commented code

2020-08-07 07:33 UTC, mosesogwo commented on app/controllers/sessions_controller.rb
> +    # @session = Session.new
Remove commented code

2020-08-07 07:33 UTC, mosesogwo commented on app/controllers/users_controller.rb
> +    set_user
_set\_user_ here seem to be unnecessary since you have _current\_user_ for use in your views.

2020-08-08 17:58 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General


##### The Users `show.html.erb` views should display the following:

* [x] lists events created by user, i.e. `@created_events = current_user.events` 
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png)


* [x] lists events previoulsy attendented by user
* [x] lists upcoming events previously attended by user 

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-08-11 01:29 UTC, Ispirett approved these changes
## Status Approved :+1: 

Great job with this project and the changes requested :+1:  :1st_place_medal: you can move along.

2020-08-11 02:36 UTC, merged